[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
aptPkgs = ["ffmpeg"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"

[[volumes]]
mountPath = "/data"
